name: Postman Tests (Newman)

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  newman:
    runs-on: ubuntu-latest
    outputs:
      pages_path: ${{ steps.pack.outputs.path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install newman + html reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman collection
        run: |
          mkdir -p newman
          newman run "postman/Postman Library API V2.postman_collection.json" \
            --reporters cli,htmlextra,junit \
            --reporter-htmlextra-export "newman/report.html" \
            --reporter-junit-export "newman/results.xml"

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman/
          if-no-files-found: error

      - name: Prepare Pages artifact
        id: pack
        run: |
          echo "path=newman" >> "$GITHUB_OUTPUT"

  deploy-pages:
    needs: newman
    if: ${{ success() }}    # only publish if tests passed
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: newman

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
