name: Postman Tests (Newman)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install newman + html reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # If your collection needs a base URL or token later, add:
      #   --env-var baseUrl=https://example.com
      - name: Run Postman collection
        run: |
          mkdir -p newman
          newman run "postman/Postman Library API V2.postman_collection.json" \
            --reporters cli,htmlextra,junit \
            --reporter-htmlextra-export "newman/report.html" \
            --reporter-junit-export "newman/results.xml"

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman/
          if-no-files-found: error
