name: API Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'postman/**'
      - '.github/workflows/postman-ci.yml'
  pull_request:
    paths:
      - 'postman/**'
      - '.github/workflows/postman-ci.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install newman + html reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman collection
        run: |
          mkdir -p newman
          newman run "postman/Postman Library API V2.postman_collection.json" \
            --env-var baseUrl=https://library-api.postmanlabs.com \
            --reporters cli,htmlextra,junit \
            --reporter-htmlextra-export "newman/report.html" \
            --reporter-junit-export "newman/results.xml"

      # Downloadable CI artifact (HTML + JUnit)
      - name: Upload CI artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman/
          if-no-files-found: ignore
          retention-days: 7

      # Pages artifact for next job
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: newman

  deploy-pages:
    needs: newman
    if: ${{ success() }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
