name: Postman Tests (Newman)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install newman
        run: npm install -g newman

      - name: Run Postman collection
        run: |
          newman run "postman/Postman Library API V2.postman_collection.json" \
            --reporters cli,junit \
            --reporter-junit-export "newman-results.xml"

